# Generated by Django 3.0.5 on 2020-11-27 22:47

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('username', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SelectedMenu',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('customization', models.TextField(blank=True)),
                ('expired', models.BooleanField(default=False)),
                ('meal', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='MealDelivery.Meal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MealDelivery.Employee')),
            ],
        ),
    ]
