# Generated by Django 3.0.5 on 2020-11-29 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MealDelivery', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['name'], 'verbose_name': 'Employee', 'verbose_name_plural': 'Employees'},
        ),
        migrations.AlterModelOptions(
            name='meal',
            options={'ordering': ['date'], 'verbose_name': 'Meal', 'verbose_name_plural': 'Meals'},
        ),
        migrations.AlterModelOptions(
            name='selectedmenu',
            options={'ordering': ['date'], 'verbose_name': 'SelectedMenu', 'verbose_name_plural': 'SelectedMenus'},
        ),
        migrations.AlterField(
            model_name='selectedmenu',
            name='customization',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='selectedmenu',
            name='meal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MealDelivery.Meal'),
        ),
    ]
